print ("WARNING This Game Is A Horror Game Not A Chat Room Test You Dumb Idiot")
ok = input ("Ok Whatever.")
print ("@Player Has Joined The Chat With @Adam!")
print ("Adam:Hello!")
talk = input("Talk. ")
print ("System:Adam Has Left.")
print ("System:Him Has N0T J01N3D")
talk = input("Talk. ")
print (":H3LL0")
talk = input("Talk. ")
print("1 W1LL K1LL Y0U N0W UNL3SS Y0U D0DG3")
print ("Tip: Say D To Dodge")
dodge = input("Dodge.")
print ("*Knife Misses*")
print (":H3H N0T S0 B4D..")
print("You:BUT STILL WHO THE #### ARE YOU!?")
print (":Y0U W1LL N3V3R KN0W")
print ("Tip: Say D To Dodge")
dodge = input("Dodge.")
print ("*Knife Misses*")
print (":1 W1LL #####NG K1LL Y0-")
print ("ERROR: No Internet Cable Connected Your Chat With @ Has Broke. Check Output Log For More Details.")
print ("Opening Chat With @Adam Please Wait...")
print ("@Player Has Joined The Chat With @Adam!")
print ("Adam:Hello!")
print ("You:Not Again...")
print ("End Of Chapter 1")
print ("But This Is Not The End....")
print ("There Is More To See In Chapter 2...")
end = input ("yay you beat the game good job")